#!/bin/bash

echo "🌐 腾讯云EdgeOne Pages部署指南"
echo ""
echo "📋 部署步骤："
echo "1. 访问 https://console.cloud.tencent.com/edgeone"
echo "2. 注册/登录腾讯云账号"
echo "3. 开通EdgeOne服务（免费版）"
echo "4. 创建站点："
echo "   - 站点名称: recruitment-system"
echo "   - 接入方式: CNAME接入"
echo "5. 进入 '边缘函数' > 'Pages'"
echo "6. 创建Pages项目："
echo "   - 项目名称: recruitment-frontend"
echo "   - 连接GitHub仓库"
echo "   - 分支: deployment"
echo "   - 构建命令: cd frontend && npm install && npm run build"
echo "   - 输出目录: frontend/build"
echo "7. 配置环境变量（从 deploy/config/.env.production 复制）"
echo "8. 部署完成后配置自定义域名"
echo ""
echo "🔧 自动化部署（可选）："
echo "也可以直接上传 frontend/build 目录到任何静态托管服务"