#!/bin/bash

echo "🌐 免费域名申请指南"
echo ""
echo "📋 推荐方案：eu.org 二级域名"
echo "1. 访问 https://nic.eu.org"
echo "2. 点击 'New Domain'"
echo "3. 填写域名信息："
echo "   - Domain: your-project-name.eu.org"
echo "   - Admin Contact: 您的邮箱"
echo "   - Technical Contact: 您的邮箱"
echo "4. 设置DNS服务器为Cloudflare："
echo "   - ns1.cloudflare.com"
echo "   - ns2.cloudflare.com"
echo "5. 提交申请（需要人工审核，通常1-7天）"
echo ""
echo "🔄 备选方案："
echo "- publicvm.com (https://freedomain.one)"
echo "- nom.za (https://www.nom.za)"
echo "- pp.ua (https://nic.ua)"