#!/bin/bash

echo "☁️ Cloudflare CDN配置指南"
echo ""
echo "📋 配置步骤："
echo "1. 访问 https://www.cloudflare.com"
echo "2. 注册/登录账号"
echo "3. 添加站点：输入您的域名"
echo "4. 选择免费计划"
echo "5. 配置DNS记录："
echo "   - A记录: @ -> 您的前端IP地址"
echo "   - CNAME记录: api -> 您的后端域名"
echo "   - CNAME记录: www -> 您的域名"
echo "6. 启用以下功能："
echo "   - Always Use HTTPS: ON"
echo "   - Auto Minify: CSS, JS, HTML"
echo "   - Brotli Compression: ON"
echo "   - Browser Cache TTL: 4 hours"
echo "7. 等待DNS传播（通常5-10分钟）"
echo ""
echo "🔍 验证配置："
echo "curl -I https://your-domain.eu.org"